/**
 *  All action types for therapist auth operations
 */

// sets state values
export const SET_THERAPIST_USER = 'SET_THERAPIST_USER';
export const SET_THERAPIST_LOADING_STATUS = 'SET_THERAPIST_LOADING_STATUS';
export const SET_THERAPIST_AUTH_STATUS = 'SET_THERAPIST_AUTH_STATUS';
export const SET_THERAPIST_AUTH_SUCCESS = 'SET_THERAPIST_AUTH_SUCCESS';
export const SET_THERAPIST_AUTH_ERROR = 'SET_THERAPIST_AUTH_ERROR';
export const SET_THERAPIST_ALERT_TYPE = 'SET_THERAPIST_ALERT_TYPE';
